# Generated by Django 5.2.1 on 2025-09-17 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(limit_choices_to={'user_type': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_admins', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'USER'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
