# Generated by Django 5.2.1 on 2025-09-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tma', '0002_adminmanage'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='adminmanage',
            constraint=models.UniqueConstraint(fields=('admin', 'user'), name='unique_admin_user_pair'),
        ),
    ]
